# Generated by Django 6.0 on 2025-12-05 01:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('device_id', models.IntegerField(primary_key=True, serialize=False, verbose_name='ID do dispositivo')),
                ('name', models.CharField(max_length=50, verbose_name='Nome do dispositivo')),
                ('port', models.SmallIntegerField(verbose_name='Porta')),
                ('analog_value', models.PositiveSmallIntegerField(default=0, verbose_name='Valor analógico (0-255)')),
                ('digital_value', models.BooleanField(default=False, verbose_name='Valor digital')),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Cômodo')),
                ('status', models.BooleanField(verbose_name='Status')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
        ),
    ]
