# Generated by Django 6.0 on 2025-12-05 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='device_type',
            field=models.BooleanField(default=False, verbose_name='Atuador(0)|Sensor(1)'),
        ),
    ]
