# Generated by Django 6.0 on 2025-12-05 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_remove_room_status_device_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='device_input',
            field=models.BooleanField(default=False, verbose_name='Analogico(0)|Digital(1)'),
        ),
    ]
